export const maxImageIndex = 12

export const wantedLevelMessages = [
    [
        "Man, I'm a real celebrity!",
        "Looks like I'm a wanted man!",
        "I'm not even a criminal!",
        "What did I do this time?",
        "I must be in the wrong place at the wrong time.",
        "Who knew I was this popular!",
        "Guess I'm making a name for myself.",
        "It's like I'm famous or something!",
        "I'm a wanted man and I love it!",
        "Must have been something I said.",
        "I must have made someone really mad!",
        "I'm practically a celebrity!",
        "What did I do to deserve this?",
        "That escalated quickly!",
        "I'm a wanted man on the run!"
    ],
    [
        "I think I'm in hot water now!",
        "Uh oh, I think I'm wanted!",
        "Time to make like a banana and split.",
        "I'm feeling a little bit toasty!",
        "I'm in deep trouble now!",
        "This isn't gonna end well...",
        "I'm in the sights of the authorities!",
        "I'm at boiling point now!",
        "Time to get out of Dodge!",
        "I'm in the crosshairs now!",
        "I'm on the wrong side of the law!",
        "I'm about to feel the heat!",
        "I'm wanted - wanted dead or alive!",
        "I'm in the sights of the law!",
        "I better watch my back!"
    ],
    [
        "Oh great, now I'm wanted level 3! I must be pretty important.",
        "Oh no, I'm wanted level 3 now! I guess I'm no longer a wanted man.",
        "I'm wanted level 3 now? I'm getting pretty close to being a wanted criminal.",
        "Wanted level 3? That's a lot of heat, I'd better watch my back.",
        "I'm wanted level 3 now, better keep an eye out for the cops.",
        "Wanted level 3, oh boy this is getting serious!",
        "Wow, I'm wanted level 3, I'm getting famous!",
        "Well, I'm wanted level 3 now, so I guess I'm not as innocent as I thought.",
        "Oh great, now I'm wanted level 3. I should have known better than to commit crimes.",
        "I'm wanted level 3, I'd better start running.",
        "Wanted level 3? Looks like I'm in for a wild ride!",
        "Wanted level 3? Time to hide!",
        "I'm wanted level 3 now? I guess I'm not so popular with the law anymore.",
        "Wanted level 3? I'm in trouble now!",
        "Wanted level 3? Looks like I've gone too far this time."
    ],
    [
        "Oh no, I'm wanted level 4 now - looks like I'm in hot water!",
        "I didn't realize being a little mischievous would escalate to wanted level 4!",
        "I knew I shouldn't have stolen that sandwich...now I'm wanted level 4.",
        "I think I'm in trouble - I'm wanted level 4 now!",
        "I'm wanted level 4 now - who knew the cops could catch me so quickly?",
        "I'm wanted level 4 - guess I'm a wanted man now!",
        "Wanted level 4 - looks like I'm a wanted criminal now!",
        "I'm wanted level 4 - I think I'm wanted for questioning now!",
        "Wanted level 4 - time to get out of town!",
        "I'm wanted level 4 - I better hide!",
        "Wanted level 4 - please don't arrest me!",
        "I'm wanted level 4 - yikes, I'm in deep trouble now!",
        "Wanted level 4 - I'm sure the police are after me now!",
        "Wanted level 4 - I think the author is trying to tell me something!",
        "I'm wanted level 4 - looks like I'm in for an adventure now!"
    ],
    [
        "Run, Forest, Run!",
        "I'm so wanted they made me wanted level 5!",
        "Time to skedaddle!",
        "Well, I guess it's time to go on the lam!",
        "I'm a wanted man on the run!",
        "Oh no, here come the cops!",
        "I'm burning rubber, and my wanted level is 5!",
        "This is the heat I can't beat!",
        "Guess I'm the most wanted man in town!",
        "I've got the fuzz on my tail!",
        "Time to jump the border!",
        "I'm one step ahead of the law!",
        "It's time to vamoose!",
        "I'm wanted like a celebrity!",
        "I'm the most wanted man in the city!"
    ],
    [
        "Hey foreign agents, looks like you won't be getting away this time - Alexey Navalny is on the case!",
        "Alexey Navalny has you surrounded - better surrender!",
        "We've got you surrounded, foreign agents - time to face the music!",
        "Alexey Navalny has caught up with you - no escape now!",
        "There's nowhere to run, foreign agents - Alexey Navalny is here!",
        "Alexey Navalny is one step ahead of you - wanted level 6!",
        "You can't hide from Alexey Navalny - it's time to face the consequences!",
        "Alexey Navalny is coming for you - the game is up!",
        "Alexey Navalny has tracked you down - wanted level 6!",
        "You thought you could get away with it, foreign agents - but Alexey Navalny is here!",
        "Alexey Navalny is here to take you down - wanted level 6!",
        "Looks like you're in trouble, foreign agents - Alexey Navalny is on the case!",
        "You thought you could outsmart Alexey Navalny - think again!",
        "You can run, but you can't hide - Alexey Navalny is here!",
        "Alexey Navalny has caught up with you - wanted level 6!"
    ]
]
